nombre= input("Ingrese su  nombre:")
apellido= input("Ingrese su apellido:")
seccion= input ("Ingrese su seccion:")
sede= input ("Ingrese su sede:")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("Codigo y seccion:", seccion)
print("Sede:", sede)
